# Generated by Django 3.1.2 on 2020-12-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapist_special_hour',
            name='day',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='therapist_special_hour',
            name='endtime',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='therapist_special_hour',
            name='starttime',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
