# Generated by Django 3.1.2 on 2020-12-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0003_auto_20201204_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
